// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "gitlab.com/prosa-backend-test/video_converter/domain"

	multipart "mime/multipart"
)

// VideoUsecase is an autogenerated mock type for the VideoUsecase type
type VideoUsecase struct {
	mock.Mock
}

// Convert provides a mock function with given fields: file, op
func (_m *VideoUsecase) Convert(file *multipart.FileHeader, op domain.OutputPreset) (string, error) {
	ret := _m.Called(file, op)

	var r0 string
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, domain.OutputPreset) string); ok {
		r0 = rf(file, op)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, domain.OutputPreset) error); ok {
		r1 = rf(file, op)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
